services:
  - type: web
    name: biblioteca-inteligente-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd biblioteca-inteligente-backend && npm install
    startCommand: cd biblioteca-inteligente-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_KEY
        sync: false
      - key: TU_SERVICE_ID
        sync: false
      - key: TU_TEMPLATE_ID
        sync: false
      - key: TU_PUBLIC_KEY
        sync: false
